### ISSUE TITLE
SSK Validation Bug

### ISSUE THREAD

**Issue by virenerus** [knub/onehundredandtwenty#17]
There seems to be a bug in the SSK validation.
I have an invalid plan of SSK courses that the algorithm validates:
* WS14/15:
  * Business Etikette
  * Persönlichkeit & Selbstmanagement
  * Personal Management
* SS15:
  * English Level 3
  * Überzeugend Präsentieren

Also the algorithm seems not to check if the combination of SSK is valid in regard to the maximum number of CP per SSK category.

**Comment by knub** [comment]
@120-team @jfrohnhofen @jw8tel: Can you investigate?

**Comment by psieg** [comment]
PR should fix the invalid validations.
About the maximum: I'm not sure how the rules are there: 
* One needs at least 3 CP in each group. In that case 4x3 make the necessary 12 and it's enough to check for the minimum, having more is no problem

*OR*
* 3 is merely the minimum of points a course in the respective group would get you. You can actually mix as you wish, but have at max. 6 (12 for DT) cp per group, so one could theoretically get all SSK points from Design Thinking. In that case a more complicated rule is necessary.

Does someone know?

**Comment by knub** [comment]
Merged the pull request. Can you check tomorrow, @virenerus?

I agree with @psieg, that having more than the allowed number of LP in one SSK module does not make an invalid plan. However, if for example I select more than 6 LP in SSK-KO, then that should not count towards the whole 12 LP necessary.

Regarding the interpretation of the rule:
I think and hope that the latter interpretation is correct. Otherwise the whole rule could be simplified to "Just make 3 LP in every module". No one does more SSK courses than necessary :-).
However, I just wrote to Studienreferat to clear up matters.

*PS: I just mentioned every account I could find in the commit history ;). Will use* `psieg` *in the future*.

**Comment by knub** [comment]
Answer, confirming my interpretation:
"ein Modul hat die Größe 3 LP oder 6LP.
Sie können die „weiteren“ 12LP  erwerben, indem Sie z.Bsp. alle 4 „weiteren“ Module mit je 3LP befüllen... oder 2 Module mit jeweils 6LP befüllen – z.Bsp. SSK-Recht  und SSK-Ko."
