### ISSUE TITLE
Variants for different Vertiefungsgebiete do not show which lectures are used

### ISSUE THREAD

**Issue by kirstin** [knub/onehundredandtwenty#21]
I know in onehundredandeighty different variants also showed which lectures were used for which Vertiefungsgebiet, and how many points were made in this Vertiefungsgebiet exactly.

For onehundredandtwenty it would be interesting to show which lectures were used for the two Vertiefungsgebiete, as well as which lectures were used to fill the ITSE requirement.

Also I would like for ITSE to be treated more equal to the other two needed Vertiefungsgebiete. This means, if points are missing to complete the Belegung, also indicate, that 24 points are needed in ITSE.

**Comment by kirstin** [comment]
I mean, once a Belegung is valid.

**Comment by psieg** [comment]
The problem about this, especially when including ITSE, is that the table will explode. One single option in 180 can be built with 4 lectures (12+12). A valid combination in 120 requires at least 11 courses (24+24+15) per combination. Since most courses can be ITSE or one VT (worst case all three) the number of combination grows exponentially, even in 180 having a single lecture too much can get you 8 variants:
![untitled](https://cloud.githubusercontent.com/assets/5766601/7134171/92a0b270-e29a-11e4-90e4-ff7ef998aa9d.png)


There is a message if you do not have 24 CP in ITSE. You will however most likely not see it because ITSE is filled first (with courses you expected to be in a VT)

**Comment by knub** [comment]
Yes, I think this requires some serious thinking about optimization and GUI.
I don't see me doing that in the next time.
For me, I build an excel sheet to try different settings: http://goo.gl/629e7E

**Comment by kirstin** [comment]
I know ITSE is filled first. However, I would like to have the message concerining ITSE continue displaying, since both Vetiefungsgebiete might be filled adequately if just one ITSE is taken additionally. I just think ITSE is very similar to the two Vertiefungsgebiete and should be treated more equal to them.

I had more than 8 optins in 180, but I did not mind that. I just like having the information over not having the information. Maybe, if you do not want to display the information on the same page, offer to either download the different variants in some file format that is human readable or offer maybe a popup that shows which courses were used to fill which Vertiefungsgebiet. I do not think the UI would need much change, just a link maybe to either download or open a popup.
